### CREATE USER

POST http://localhost:8888/api/v1/users
Content-Type: application/json

{
  "name": "Jay",
  "age": 25
}

### GET USERS

GET http://localhost:8888/api/v1/users/

### PUT USERS

PUT http://localhost:8888/api/v1/users/1
Content-Type: application/json

{
  "age": 99
}